name: Build artifacts
on: push

env:
  build_type: "Release"

jobs:
  linux:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    container: ubuntu:rolling
    env:
      DEBIAN_FRONTEND: "noninteractive"
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Ubuntu GCC",
            artifact: "linux-gcc.tar.xz"
          }
    steps:
      - name: Update environment
        shell: bash
        run: |
          # Update package lists
          apt-get update
          # Install build tools
          apt-get install -y apt-utils software-properties-common
          apt-get dist-upgrade -y
          apt-get install -y build-essential gcc g++ make cmake python3-pip
          pip3 install conan
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure CMake
        shell: bash
        run: |
          cmake . \
            -Bbuild \
            -DCMAKE_BUILD_TYPE=${{ env.build_type }} \
            ${{ matrix.config.cmake_configure_options }}
      - name: Build
        shell: bash
        run: |
          cd build
          make
          cd ..
      - name: Prepare upload
        run: |
          tar cfz ${{ matrix.config.artifact }} build
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.config.artifact }}
          name: ${{ matrix.config.artifact }}
