name: Build and run unit tests

on:
  pull_request:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install conan
        run: pip3 install conan

      - name: Build test binary
        run: |
          mkdir build
          cmake -B build -S . -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=./conan_provider.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Run tests
        run: ./build/test/algorithms_tests
