name: Build and run unit tests in Docker env
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        shell: bash
        run: docker build --file .github/ci_files/Dockerfile --tag tester .

      - name: Run tests
        shell: bash
        run: docker run tester
