name: Build and run unit tests in Docker linux env
on: push

jobs:
  docker_build_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          tags: autotester
          file: .github/workflows/Dockerfile
          context: .
      - name: Run tests
        shell: bash
        run: docker run autotester