name: Basic autotest
on:
  workflow_run:
    workflows: ["Build artifacts"]
    types:
      - completed

jobs:
  linux:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    container: ubuntu:rolling
    env:
      DEBIAN_FRONTEND: "noninteractive"
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Ubuntu GCC",
            artifact: "linux-gcc.tar.xz"
          }
    steps:
      - name: Download builded artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.config.artifact }}
      - name: Build
        shell: bash
        run: ./algorithms_tests
